stages:
- name: 构建docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dockerhub.izaodao.com/seldoon/nginx:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: dockerhub.izaodao.com
    env:
      PLUGIN_INSECURE: "true"
  when:
    branch:
      include:
      - master
- name: 部署
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
