stages:
- name: 构建docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: seldoon/rancher:v2
      pushRemote: true
      registry: hub.docker.com
    env:
      PLUGIN_DEBUG: true
      PLUGIN_INSECURE: true
  when:
    branch:
      include:
      - master
- name: 部署
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 30
notification: {}
